# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='room',
            field=models.IntegerField(default=0),
        ),
    ]
