# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-10 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20160610_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_num',
            name='my_number',
        ),
        migrations.AddField(
            model_name='player_num',
            name='mynumber',
            field=models.IntegerField(default=123, unique=True),
        ),
        migrations.AlterField(
            model_name='number_room1',
            name='guess_number',
            field=models.IntegerField(default=123, unique=True),
        ),
        migrations.AlterField(
            model_name='number_room10',
            name='guess_number',
            field=models.IntegerField(default=123, unique=True),
        ),
        migrations.AlterField(
            model_name='number_room2',
            name='guess_number',
            field=models.IntegerField(default=123, unique=True),
        ),
        migrations.AlterField(
            model_name='number_room3',
            name='guess_number',
            field=models.IntegerField(default=123, unique=True),
        ),
        migrations.AlterField(
            model_name='number_room4',
            name='guess_number',
            field=models.IntegerField(default=123, unique=True),
        ),
        migrations.AlterField(
            model_name='number_room5',
            name='guess_number',
            field=models.IntegerField(default=123, unique=True),
        ),
        migrations.AlterField(
            model_name='number_room6',
            name='guess_number',
            field=models.IntegerField(default=123, unique=True),
        ),
        migrations.AlterField(
            model_name='number_room7',
            name='guess_number',
            field=models.IntegerField(default=123, unique=True),
        ),
        migrations.AlterField(
            model_name='number_room8',
            name='guess_number',
            field=models.IntegerField(default=123, unique=True),
        ),
        migrations.AlterField(
            model_name='number_room9',
            name='guess_number',
            field=models.IntegerField(default=123, unique=True),
        ),
    ]
