# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20160611_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='number_room',
            name='cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='number_room',
            name='room',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='number_room',
            name='ball',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='number_room',
            name='strike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='cnt',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='player_num',
            name='cnt',
            field=models.IntegerField(default=1),
        ),
    ]
