# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20160612_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number_room',
            name='cnt',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='number_room',
            name='guess_number',
            field=models.IntegerField(default=123),
        ),
    ]
